spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/hiwipay'
    username: postgres
    password: postgres
  flyway:
    enabled: false
app:
  cron:
    enabled: false
cloud:
  azure:
    storage:
      blob:
        account-name: 'hiwistoragepreprod'
        account-key: 'S3bGImuY9GjBU5UjlcUjogYQ2THI/5s/2GQLh7AdKKSCWIKMiC+8nejzvRXGoFtHXJRZQ8TIs8qE+AStWLcBrA=='
        endpoint: 'https://hiwistoragepreprod.blob.core.windows.net/'
        container-name: 'blobcontainer'
        connection-string: 'DefaultEndpointsProtocol=https;AccountName=hiwistoragepreprod;AccountKey=S3bGImuY9GjBU5UjlcUjogYQ2THI/5s/2GQLh7AdKKSCWIKMiC+8nejzvRXGoFtHXJRZQ8TIs8qE+AStWLcBrA==;EndpointSuffix=core.windows.net'
