spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/hiwipay'
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        default_schema: transaction_service
  flyway:
    enabled: false
    baselineOnMigrate: true
    defaultSchema: 'transaction_service'
logging:
  level:
    org:
      springframework:
        web: debug
      hibernate: error
